default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: toshikiokabe_development
test:
  <<: *default
  database: toshikiokabe_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
