version: '3'

volumes:
  database: {}

services:
  app:
    build: .
    image: windyakin-app:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql2://root:root@database/?encoding=utf8mb4&charset=utf8mb4&collation=utf8mb4_general_ci
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
